Core_MVC_Bootstrap/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.DAL.Data;
using App.DAL.Models;
using System.Data;
using Microsoft.EntityFrameworkCore.Storage;
using App.BLL.Services;
using App.BLL.ServiceContracts;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using App.Home.FileUploadService;
using Microsoft.AspNetCore.Authorization;

namespace App.Home.Controllers
{
    //[Authorize]
    public class GalleryController : Controller
    {
        private readonly MHDBContext _context;
        private readonly IGalleryService _galleryService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IFileUploadService _fileUploadService;


        public GalleryController(IGalleryService galleryService, MHDBContext mHDBContext, IWebHostEnvironment webHostEnvironment, IFileUploadService fileUploadService)
        {
            this._galleryService = galleryService;
            this._context = mHDBContext;
            this._fileUploadService = fileUploadService;


        }

        // GET: Directors
        public async Task<IActionResult> GalleryPhotoIndex()
        {
            List<TblGalleryPhoto> tblGalleryPhotos = await _galleryService.GetAllGallery();



            return View(tblGalleryPhotos);
        }
        public async Task<IActionResult> GetGalleryPhoto(int id)
        {
            //List<TblGalleryPhoto> tblGalleryPhotos = await _galleryService.GetAllGallery();


            var tblGalleryPhoto = await _context.TblGalleryPhoto.FindAsync(id);
            tblGalleryPhoto.IsDelete = true;
            _context.Update(tblGalleryPhoto);
            await _context.SaveChangesAsync();


            return new JsonResult(tblGalleryPhoto);
        }

        // GET: Directors/Create
        public IActionResult CreateGalleryPhoto()
        {
            //List<SelectListItem> category = new List<SelectListItem>()
            //{
            //    new SelectListItem { Value = "1", Text = "Certificate" },
            //    new SelectListItem { Value = "2", Text = "Random" },
            //    new SelectListItem { Value = "3", Text = "Visit" },

            //};
            List<string> category = new List<string>()
            { "Certificate" ,"Random" ,"Visit"

            };

            //assigning SelectListItem to view Bag
            ViewBag.Category = category;

            return View();
        }

        // POST: Directors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGalleryPhoto(/*[Bind("ImageId,Name,Image,Flag,IsDelete,Details,CreatedDate,CreatedBy,UpdatedDate,UpdatedBy")]*/ TblGalleryPhoto tblGalleryPhoto)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var imagePath = "";
                    if (tblGalleryPhoto.PhotoUpload != null)
                    {
                        imagePath = await _fileUploadService.UploadImageGallery(tblGalleryPhoto);
                        tblGalleryPhoto.Image = imagePath;
                    }
                    //tblGalleryPhoto = await _galleryService.CreateGalleryPhoto(tblGalleryPhoto);
                    List<string> category = new List<string>()
            { "Certificate" ,"Random" ,"Visit"

            };

                    //assigning SelectListItem to view Bag
                    ViewBag.Category = category;

                    //CommonService.SetCommonFields(tblGalleryPhoto);
                    tblGalleryPhoto.IsDelete = false;
                    tblGalleryPhoto.CreatedBy = 1;
                    tblGalleryPhoto.CreatedDate = DateTime.Now;


                    _context.Add(tblGalleryPhoto);
                    await _context.SaveChangesAsync();
                }
                catch
                {
                    throw;
                }
                //_directorsService.CreateDirectors(tblGalleryPhoto);

                return RedirectToAction(nameof(GalleryPhotoIndex));
            }
            return View(tblGalleryPhoto);
        }

        // GET: Directors/Edit/5
        public async Task<IActionResult> EditGalleryPhoto(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblGalleryPhoto = await _context.TblGalleryPhoto.FindAsync(id);
            if (tblGalleryPhoto == null)
            {
                return NotFound();
            }
            return View(tblGalleryPhoto);
        }

        // POST: Directors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditGalleryPhoto(int id, /*[Bind("ImageId,Name,Image,Flag,IsDelete,Details,CreatedDate,CreatedBy,UpdatedDate,UpdatedBy")]*/ TblGalleryPhoto tblGalleryPhoto)
        {
            if (id != tblGalleryPhoto.ImageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //using (IDbContextTransaction transaction = _context.Database.BeginTransaction()) {
                    //    transaction.Commit();
                    //    transaction.Rollback();
                    //}
                    var imagePath = "";
                    if (tblGalleryPhoto.PhotoUpload != null)
                    {
                        imagePath = await _fileUploadService.UploadImageGallery(tblGalleryPhoto);
                        tblGalleryPhoto.Image = imagePath;
                    }
                    tblGalleryPhoto = await _galleryService.UpdateGalleryPhoto(tblGalleryPhoto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblDirectorsExists(tblGalleryPhoto.ImageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(GalleryPhotoIndex));
            }
            return View(tblGalleryPhoto);
        }

        //GET: Directors/Delete/5
        public async Task<IActionResult> GalleryphotoDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblGalleryPhoto = await _context.TblGalleryPhoto
                .FirstOrDefaultAsync(m => m.ImageId == id);
            if (tblGalleryPhoto == null)
            {
                return NotFound();
            }
            else
            {
                await GalleryPhotoDelete(tblGalleryPhoto.ImageId);
            }

            return RedirectToAction(nameof(GalleryPhotoIndex));
        }

        // POST: Directors/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GalleryPhotoDelete(int id) 
        {
            //var tblGalleryPhoto = await _context.TblDirectors.FindAsync(id);
            //_context.TblDirectors.Remove(tblGalleryPhoto);
            //await _context.SaveChangesAsync();


            var tblGalleryPhoto = await _context.TblGalleryPhoto.FindAsync(id);
            tblGalleryPhoto.IsDelete = true;
            _context.Update(tblGalleryPhoto);
            await _context.SaveChangesAsync();



            return View(tblGalleryPhoto);
        }
        

        private bool TblDirectorsExists(int id)
        {
            return _context.TblDirectors.Any(e => e.DirectorId == id);
        }
    }
}

Core_MVC_Bootstrap/Views/Gallery/CreateGalleryPhoto.cshtml
@model App.DAL.Models.TblGalleryPhoto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
 

<div class="box-content">
    <div class="box-heading">
        <div class="box-title">
            <h3 class="mb-35">Add Gallery Photo</h3>
        </div>
        <div class="box-breadcrumb">
            <a class="btn btn-dark" asp-action="GalleryPhotoIndex">Back to List</a>
        </div>
    </div>
    <div class="row">
        <div class="form-control">
            <form asp-action="CreateGalleryPhoto" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" required />
                    <small class="text-muted">------Max 50 character---</small>

                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
             
                @*<div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input asp-for="Image" class="form-control" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label class="control-label">Upload Photo</label>
                    <input type="file" name="PhotoUpload" data-member="PhotoUpload" asp-for="PhotoUpload" class="form-control" required/>
                    <span asp-validation-for="PhotoUpload" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Category</label>
                    <select asp-for="Flag" name="category" class="form-control" asp-items="new SelectList(ViewBag.Category)" required>
                       <option value=""> --- Select One ---</option>
                    </select>
                    
                   @* <input asp-for="Flag" class="form-control" required/>*@
                    <span asp-validation-for="Flag" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Details" class="control-label"></label>
                    <textarea asp-for="Details" class="form-control" rows="5" required maxlength="500"></textarea>
                    <small class="text-muted">------Max 500 character---</small>
                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

</div>

Core_MVC_Bootstrap/Views/Gallery/Delete.cshtml
@model App.DAL.Models.TblGalleryPhoto

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblGalleryPhoto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Flag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDelete)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDelete)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ImageId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Core_MVC_Bootstrap/Views/Gallery/Details.cshtml
@model App.DAL.Models.TblGalleryPhoto

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>TblGalleryPhoto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Flag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDelete)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDelete)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ImageId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Core_MVC_Bootstrap/Views/Gallery/EditGalleryPhoto.cshtml
@model App.DAL.Models.TblGalleryPhoto

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}



<div class="box-content">
    <div class="box-heading">
        <div class="box-title">
            <h3 class="mb-35">Update Gallery photo</h3>
        </div>
        <div class="box-breadcrumb">
            <a class="btn btn-dark" asp-controller="Gallery" asp-action="GalleryPhotoIndex">Back to List</a>
        </div>
    </div>
    <div class="row">
        <div class="form-control">
            <div class="box-padding">
            <form asp-action="EditGalleryPhoto" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ImageId" />
                <input type="hidden" asp-for="Image" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label mb-5"></label>
                    <input asp-for="Name" class="form-control" maxlength="50" />
                    <small class="text-muted">------Max 50 character---</small>

                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <img src="@Model.Image" height="150" width="300" />
                <div class="form-group">
                    <label class="control-label">Change Profile Image</label>
                    <input id="PhotoUpload" name="PhotoUpload" data-member="PhotoUpload" asp-for="PhotoUpload" class="form-control" />
                    <span asp-validation-for="PhotoUpload" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Flag" class="control-label"></label>
                    <input asp-for="Flag" class="form-control" />
                    <span asp-validation-for="Flag" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Details" class="control-label"></label>
                    @*<input asp-for="Details" class="form-control" />*@
                    <textarea asp-for="Details" class="form-control" rows="5" maxlength="500"></textarea>
                        <small class="text-muted">------Max 500 character---</small>

                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-secondary" />
                </div>

            </form>

        </div>
        </div>
    </div>
</div>

Core_MVC_Bootstrap/Views/Gallery/GalleryPhotoIndex.cshtml
@model IEnumerable<App.DAL.Models.TblGalleryPhoto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@section scripts{
    <script src="~/Scripts/Gallery/GalleryPhotoIndex.js"></script>
}

    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>



    @*<table class="table">
    <thead>
    <tr>
    <th>
    @Html.DisplayNameFor(model => model.Name)
    </th>
    <th>
    @Html.DisplayNameFor(model => model.Image)
    </th>
    <th>
    @Html.DisplayNameFor(model => model.Flag)
    </th>
    <th>
    @Html.DisplayNameFor(model => model.IsDelete)
    </th>
    <th>
    @Html.DisplayNameFor(model => model.Details)
    </th>
    <th>
    @Html.DisplayNameFor(model => model.CreatedDate)
    </th>
    <th>
    @Html.DisplayNameFor(model => model.CreatedBy)
    </th>
    <th>
    @Html.DisplayNameFor(model => model.UpdatedDate)
    </th>
    <th>
    @Html.DisplayNameFor(model => model.UpdatedBy)
    </th>
    <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
    <tr>
    <td>
    @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
    @Html.DisplayFor(modelItem => item.Image)
    </td>
    <td>
    @Html.DisplayFor(modelItem => item.Flag)
    </td>
    <td>
    @Html.DisplayFor(modelItem => item.IsDelete)
    </td>
    <td>
    @Html.DisplayFor(modelItem => item.Details)
    </td>
    <td>
    @Html.DisplayFor(modelItem => item.CreatedDate)
    </td>
    <td>
    @Html.DisplayFor(modelItem => item.CreatedBy)
    </td>
    <td>
    @Html.DisplayFor(modelItem => item.UpdatedDate)
    </td>
    <td>
    @Html.DisplayFor(modelItem => item.UpdatedBy)
    </td>
    <td>
    <a asp-action="Edit" asp-route-id="@item.ImageId">Edit</a> |
    <a asp-action="Details" asp-route-id="@item.ImageId">Details</a> |
    <a asp-action="Delete" asp-route-id="@item.ImageId">Delete</a>
    </td>
    </tr>
    }
    </tbody>
    </table>*@




    <div class="box-content">

        <div class="box-heading">
            <div class="box-title">
                <h3 class="mb-35">Gallery Photos</h3>
            </div>
            <div class="box-breadcrumb">
                <a class="btn btn-default" asp-controller="Gallery" asp-action="CreateGalleryPhoto">Add Photo</a>
            </div>
        </div>

        <div class="row">

            <div class="col-xl-12 col-12">
                <div class="card-grid-2 hover-up">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="box-padding">
                                <div class="row display-list">
                                    <div class="table-responsive">
                                        <table id="photoList" class="stripe row-border">
                                            <thead align="center">
                                                <tr>
                                                    <th>
                                                        Name
                                                    </th>

                                                    <th>
                                                        Category
                                                    </th>
                                                    <th>
                                                        Details
                                                    </th>
                                                    <th>
                                                        Image
                                                    </th>
                                                    <th>
                                                        Action
                                                    </th>

                                                </tr>
                                            </thead>
                                            <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        <p class="color-text-paragraph font-sm" align="justify">@Html.DisplayFor(modelItem => item.Name)</p>
                                                    </td>
                                                    <td>
                                                        <p class="color-text-paragraph font-sm" align="justify"> @Html.DisplayFor(modelItem => item.Flag)</p>
                                                    </td>

                                                    <td>
                                                        <p class="color-text-paragraph font-sm" align="justify">@Html.DisplayFor(modelItem => item.Details)</p>
                                                    </td>
                                                    <td>

                                                        <p>&nbsp;</p><img src="@item.Image" style="display: block;" />

                                                    </td>
                                                    <td>
                                                        <a asp-action="EditGalleryPhoto" class="" asp-route-id="@item.ImageId"><i class='fas fa-edit' style='font-size:25px;color:black'></i></a> |
                                                        <a onclick="btnDelete(@item.ImageId)"><i class='fas fa-trash-alt' style='font-size:25px;color:red'></i></a>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>

<link href="~/customcss.css" rel="stylesheet" />