Core_MVC_Bootstrap/Controllers/DirectorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.DAL.Data;
using App.DAL.Models;
using System.Data;
using Microsoft.EntityFrameworkCore.Storage;
using App.BLL.Services;
using App.BLL.ServiceContracts;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using App.Home.FileUploadService;

namespace App.Home.Controllers
{
    public class DirectorsController : Controller
    {
        private readonly MHDBContext _context;
        private readonly IDirectorsService _directorsService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IFileUploadService _fileUploadService;


        public DirectorsController(IDirectorsService directorsService, MHDBContext mHDBContext, IWebHostEnvironment webHostEnvironment, IFileUploadService fileUploadService)
        {
            this._directorsService = directorsService;
            this._context = mHDBContext;
            this._fileUploadService = fileUploadService;


        }

        // GET: Directors
        public async Task<IActionResult> Index()
        {
            List<TblDirectors> listDirectors = await _directorsService.GetAllDirectors();
            return View(listDirectors);
        }

        // GET: Directors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Directors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(/*[Bind("DirectorId,DirectorName,Designation,CompanyPost,Image,Details,FacebookLink,TwitterLink,LinkedInLink,IsDeleted,CreatedDate,CreatedBy,UpdatedDate,UpdatedBy")]*/ TblDirectors tblDirectors)
        {
            if (ModelState.IsValid)
            {
                var imagePath = "";
                //_directorsService.CreateDirectors(tblDirectors);
                if (tblDirectors.PhotoUpload != null)
                {
                    imagePath = await _fileUploadService.UploadImageDirector(tblDirectors);
                    tblDirectors.Image = imagePath;
                }
                _context.Add(tblDirectors);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblDirectors);
        }

        // GET: Directors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblDirectors = await _context.TblDirectors.FindAsync(id);
            if (tblDirectors == null)
            {
                return NotFound();
            }
            return View(tblDirectors);
        }

        // POST: Directors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, /*[Bind("DirectorId,DirectorName,Designation,CompanyPost,Image,Details,FacebookLink,TwitterLink,LinkedInLink,IsDeleted,CreatedDate,CreatedBy,UpdatedDate,UpdatedBy,PhotoUpload")]*/ TblDirectors tblDirectors)
        {
            if (id != tblDirectors.DirectorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //using (IDbContextTransaction transaction = _context.Database.BeginTransaction()) {
                    //    transaction.Commit();
                    //    transaction.Rollback();
                    //}
                    var imagePath = "";
                    if (tblDirectors.PhotoUpload != null)
                    {
                        imagePath = await _fileUploadService.UploadImageDirector(tblDirectors);
                        tblDirectors.Image = imagePath;
                    }
                    tblDirectors = await _directorsService.UpdateDirectors(tblDirectors);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblDirectorsExists(tblDirectors.DirectorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblDirectors);
        }

        // GET: Directors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblDirectors = await _context.TblDirectors
                .FirstOrDefaultAsync(m => m.DirectorId == id);
            if (tblDirectors == null)
            {
                return NotFound();
            }

            return View(tblDirectors);
        }

        // POST: Directors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblDirectors = await _context.TblDirectors.FindAsync(id);
            _context.TblDirectors.Remove(tblDirectors);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblDirectorsExists(int id)
        {
            return _context.TblDirectors.Any(e => e.DirectorId == id);
        }
    }
}

Core_MVC_Bootstrap/Views/Directors/Create.cshtml
@model App.DAL.Models.TblDirectors

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@*<script src="~/lib/jquery/dist/jquery.js"></script>*@

<script src="~/frontend/assets/js/vendor/jquery-3.6.0.min.js"></script>
<script src="~/frontend/assets/js/vendor/jquery-migrate-3.3.0.min.js"></script>
<script src="~/Scripts/Directors/CreateDirector.js"></script>

<div class="box-content">

    <div class="box-heading">
        <div class="box-title">
            <h3 class="mb-35">Create Director</h3>
        </div>
        <div class="box-breadcrumb">
            <a class="btn btn-dark" asp-controller="Directors" asp-action="Index">Back to List</a>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
               @* <div class="form-group">
                    <label asp-for="DirectorId" class="control-label"></label>
                    <input id="" data-member="" id="" data-member="" asp-for="DirectorId" class="form-control" />
                    <span asp-validation-for="DirectorId" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label  class="control-label">Director Name</label>
                    <input id="DirectorName" data-member="DirectorName" asp-for="DirectorName" class="form-control" />
                    <span asp-validation-for="DirectorName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Designation" class="control-label"></label>
                    <input id="Designation" data-member="Designation" asp-for="Designation" class="form-control" />
                    <span asp-validation-for="Designation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CompanyPost" class="control-label"></label>
                    <input id="CompanyPost" data-member="CompanyPost" asp-for="CompanyPost" class="form-control" />
                    <span asp-validation-for="CompanyPost" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label  class="control-label">Upload Profile Image</label>
                    <input type="file" name="PhotoUpload" data-member="PhotoUpload" asp-for="PhotoUpload" class="form-control" />
                    <span asp-validation-for="PhotoUpload" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Details" class="control-label"></label>
                    <textarea asp-for="Details" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FacebookLink" class="control-label"></label>
                    <input id="" data-member="" asp-for="FacebookLink" class="form-control" />
                    <span asp-validation-for="FacebookLink" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TwitterLink" class="control-label"></label>
                    <input id="" data-member="" asp-for="TwitterLink" class="form-control" />
                    <span asp-validation-for="TwitterLink" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LinkedInLink" class="control-label"></label>
                    <input id="" data-member="" asp-for="LinkedInLink" class="form-control" />
                    <span asp-validation-for="LinkedInLink" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input id="btnSaveDirector" type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

Core_MVC_Bootstrap/Views/Directors/Delete.cshtml
@model App.DAL.Models.TblDirectors

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblDirectors</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DirectorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DirectorName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Designation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Designation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyPost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyPost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacebookLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FacebookLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TwitterLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TwitterLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedInLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkedInLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DirectorId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Core_MVC_Bootstrap/Views/Directors/Details.cshtml
@model App.DAL.Models.TblDirectors

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>TblDirectors</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DirectorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DirectorName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Designation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Designation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyPost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyPost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacebookLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FacebookLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TwitterLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TwitterLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedInLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkedInLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.DirectorId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Core_MVC_Bootstrap/Views/Directors/Directors.cshtml
@model IEnumerable<App.DAL.Models.TblDirectors>

@{
    ViewData["Title"] = "Directors";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Directors</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DirectorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Designation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyPost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Details)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FacebookLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TwitterLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LinkedInLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDeleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdatedBy)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DirectorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Designation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyPost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacebookLink)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TwitterLink)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LinkedInLink)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedBy)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DirectorId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.DirectorId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.DirectorId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Core_MVC_Bootstrap/Views/Directors/Edit.cshtml
@model App.DAL.Models.TblDirectors

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<div class="box-content">
    <div class="box-heading">
        <div class="box-title">
            <h3 class="mb-35">Update Director</h3>
        </div>
        <div class="box-breadcrumb">
            <a class="btn btn-dark" asp-controller="Directors" asp-action="Index">Back to List</a>
        </div>
    </div>
    <div class="row">
        <div class="form-control">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="DirectorId" />
                <input type="hidden" asp-for="Image" />

                <div class="form-group">
                    <label asp-for="DirectorName" class="control-label"></label>
                    <input asp-for="DirectorName" class="form-control" />
                    <span asp-validation-for="DirectorName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Designation" class="control-label"></label>
                    <input asp-for="Designation" class="form-control" />
                    <span asp-validation-for="Designation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CompanyPost" class="control-label"></label>
                    <input asp-for="CompanyPost" class="form-control" />
                    <span asp-validation-for="CompanyPost" class="text-danger"></span>
                </div>

                @*<label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />*@
                <img src="@Model.Image" height="150" width="300" />
                <div class="form-group">
                    <label class="control-label">Change Profile Image</label>
                    <input id="PhotoUpload" name="PhotoUpload" data-member="PhotoUpload" asp-for="PhotoUpload" class="form-control" />
                    <span asp-validation-for="PhotoUpload" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Details" class="control-label"></label>
                    <textarea asp-for="Details" class="form-control" rows="5"></textarea>

                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FacebookLink" class="control-label"></label>
                    <input asp-for="FacebookLink" class="form-control" />
                    <span asp-validation-for="FacebookLink" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TwitterLink" class="control-label"></label>
                    <input asp-for="TwitterLink" class="form-control" />
                    <span asp-validation-for="TwitterLink" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LinkedInLink" class="control-label"></label>
                    <input asp-for="LinkedInLink" class="form-control" />
                    <span asp-validation-for="LinkedInLink" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>

        </div>
    </div>
</div>


@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

Core_MVC_Bootstrap/Views/Directors/Index.cshtml
@model IEnumerable<App.DAL.Models.TblDirectors>

@{
    ViewData["Title"] = "Directors";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<div class="box-content">

    <div class="box-heading">
        <div class="box-title">
            <h3 class="mb-35">Directors</h3>
        </div>
        <div class="box-breadcrumb">
                <a class="btn btn-default" asp-controller="Directors" asp-action="Create">Create New</a>
        </div>
    </div>
   
    <div class="row">
        <table>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <div class="col-xl-12 col-12">
                                <div class="card-grid-2 hover-up">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12">
                                            <div class="card-grid-2-image-left">
                                                <div class="image-box"><img src="@item.Image" height="100" width="100" alt="jobBox"></div>
                                                <div class="right-info"><a class="name-job" href=""> @Html.DisplayFor(modelItem => item.DirectorName)</a><span class="location">@Html.DisplayFor(modelItem => item.Designation)</span></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-block-info">
                                         <h3>@Html.DisplayFor(modelItem => item.CompanyPost)</h3>
                                        <p class="font-sm color-text-paragraph mt-10">@Html.DisplayFor(modelItem => item.Details)</p>
                                        <div class="card-2-bottom mt-20">
                                            <div class="row">
                                                <div class="col-lg-12 col-12 text-end">
                                                    <a class="btn btn-apply-now" asp-controller="Directors" asp-action="Edit" asp-route-id="@item.DirectorId">Update</a>
                                                    @*<a class="btn btn-apply-now" href="@Url.Action("Edit/"+item.DirectorId)">Update</a>*@
                                                    @*<a class="btn btn-info"  asp-action="Details" asp-route-id="@item.DirectorId">Details</a> *@
                                                    <a class="btn btn-danger"  asp-action="Delete" asp-route-id="@item.DirectorId">Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>