Core_MVC_Bootstrap/Controllers/ExecutivesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.DAL.Data;
using App.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using App.DAL.Utilities;

namespace App.Home.Controllers
{
    //[Authorize]
    public class ExecutivesController : Controller
    {
        private readonly MHDBContext _context;
        private readonly AppUser _appUser;

        public ExecutivesController(MHDBContext context, AppUser appUser)
        {
            _context = context;
            _appUser = appUser;
        }

        // GET: Executives
        public async Task<IActionResult> ExecutiveIndex()
        {
            return View(await _context.TblExecutive.Where(x=> x.IsActive == true).ToListAsync());
        }

        // GET: Executives/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var tblExecutive = await _context.TblExecutive
        //        .FirstOrDefaultAsync(m => m.ExecutiveId == id);
        //    if (tblExecutive == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(tblExecutive);
        //}

        // GET: Executives/Create
        public IActionResult CreateExecutive()
        {
            return View();
        }

        // POST: Executives/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateExecutive(TblExecutive tblExecutive)
        {
            if (ModelState.IsValid)
            {
                
                tblExecutive.IsActive = true;
                tblExecutive.CreatedBy = _appUser.UserID;
                tblExecutive.CreatedDate = DateTime.Now;

                TblUser tblUser = new TblUser();
                tblUser.UserName = tblExecutive.Email;
                tblUser.UserPassword = tblExecutive.Password;
                _context.Add(tblUser);
                await _context.SaveChangesAsync();

                tblExecutive.UserId = tblUser.UserId;
                tblExecutive.UserRoleId = 4; //4=executive - user role
                _context.Add(tblExecutive);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ExecutiveIndex));
            }
            return View(tblExecutive);
        }

        // GET: Executives/Edit/5
        public async Task<IActionResult> EditExecutive(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblExecutive = await _context.TblExecutive.FindAsync(id);
            if (tblExecutive == null)
            {
                return NotFound();
            }
            return View(tblExecutive);
        }

        // POST: Executives/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditExecutive(int id, /*[Bind("ExecutiveId,UserRoleId,UserId,ExFirstName,ExLastName,Designation,Image,Address,Phone1,Phone2,Email,IsActive,IsApproved,CreatedDate,CreatedBy,UpdatedDate,UpdatedBy")]*/ TblExecutive tblExecutive)
        {
            if (id != tblExecutive.ExecutiveId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    tblExecutive.UpdatedBy = 1;
                    tblExecutive.UpdatedDate = DateTime.Now;
                    _context.Update(tblExecutive);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblExecutiveExists(tblExecutive.ExecutiveId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ExecutiveIndex));
            }
            return View(tblExecutive);
        }

        //GET: Directors/Delete/5
        public async Task<IActionResult> DeleteExecutive(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblExecutive = await _context.TblExecutive
                .FirstOrDefaultAsync(m => m.ExecutiveId == id);
            if (tblExecutive == null)
            {
                return NotFound();
            }
            else
            {
                await DeleteExecutive(tblExecutive.ExecutiveId);
            }

            return RedirectToAction(nameof(ExecutiveIndex));
        }

        // POST: Directors/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteExecutive(int id)
        {
            //var tblGalleryPhoto = await _context.TblDirectors.FindAsync(id);
            //_context.TblDirectors.Remove(tblGalleryPhoto);
            //await _context.SaveChangesAsync();


            var tblExecutive = await _context.TblExecutive.FindAsync(id);
            tblExecutive.IsActive = false;
            _context.Update(tblExecutive);
            await _context.SaveChangesAsync();



            return View(tblExecutive);
        }


        private bool TblExecutiveExists(int id)
        {
            return _context.TblExecutive.Any(e => e.ExecutiveId == id);
        }
    }
}

Core_MVC_Bootstrap/Views/Executives/CreateExecutive.cshtml
@model App.DAL.Models.TblExecutive

@{
    ViewData["Title"] = "Create Executives";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="box-content">
    <div class="box-heading">
        <div class="box-title">
            <h3 class="mb-35">Add Executive</h3>
        </div>
        <div class="box-breadcrumb">
            <a class="btn btn-dark" asp-action="ExecutiveIndex">Back to List</a>
        </div>
    </div>
    <div class="row">
        <div class="form-control">
            <form class="mt-30 ml-10 mr-10 mb-10" asp-action="CreateGalleryPhoto" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="UserRoleId" />
                <input type="hidden" asp-for="UserId" />

                <div class="form-group">
                    <label class="control-label">First Name</label>
                    <input asp-for="ExFirstName" class="form-control" required maxlength="50" />
                    <small class="text-muted">------Max 50 character---</small>

                    <span asp-validation-for="ExFirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Last Name</label>
                    <input asp-for="ExLastName" class="form-control" />
                    <small class="text-muted">------Max 50 character---</small>

                    <span asp-validation-for="ExLastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Designation" class="control-label"></label>
                    <input asp-for="Designation" class="form-control" />
                    <span asp-validation-for="Designation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Upload Photo</label>
                    <input type="file" name="PhotoUpload" data-member="PhotoUpload" asp-for="PhotoUpload" class="form-control" />
                    <span asp-validation-for="PhotoUpload" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" maxlength="100" />
                    <small class="text-muted">------Max 100 character---</small>

                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Phone number 1</label>
                    <input asp-for="Phone1" class="form-control" />
                    <span asp-validation-for="Phone1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Phone number 2</label>
                    <input asp-for="Phone2" class="form-control" />
                    <span asp-validation-for="Phone2" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" required/>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" required/>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="CreateExecutive" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

</div>

Core_MVC_Bootstrap/Views/Executives/EditExecutive.cshtml
@model App.DAL.Models.TblExecutive

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Edit</h1>

<h4>TblExecutive</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ExecutiveId" />
            <input type="hidden" asp-for="UserRoleId" />
            <input type="hidden" asp-for="UserId" />

            <div class="form-group">
                <label class="control-label">First Name</label>
                <input asp-for="ExFirstName" class="form-control" required maxlength="50" />
                <small class="text-muted">------Max 50 character---</small>

                <span asp-validation-for="ExFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Last Name</label>
                <input asp-for="ExLastName" class="form-control" />
                <small class="text-muted">------Max 50 character---</small>

                <span asp-validation-for="ExLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Designation" class="control-label"></label>
                <input asp-for="Designation" class="form-control" />
                <span asp-validation-for="Designation" class="text-danger"></span>
            </div>
            <img src="@Model.Image" height="150" width="300" />
            <div class="form-group">
                <label class="control-label">Change Profile Image</label>
                <input id="PhotoUpload" name="PhotoUpload" data-member="PhotoUpload" asp-for="PhotoUpload" class="form-control" />
                <span asp-validation-for="PhotoUpload" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" maxlength="100" />
                <small class="text-muted">------Max 100 character---</small>

                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Phone number 1</label>
                <input asp-for="Phone1" class="form-control" />
                <span asp-validation-for="Phone1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Phone number 2</label>
                <input asp-for="Phone2" class="form-control" />
                <span asp-validation-for="Phone2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" required />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" required />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Core_MVC_Bootstrap/Views/Executives/ExecutiveIndex.cshtml
@model IEnumerable<App.DAL.Models.TblExecutive>

@{
    ViewData["Title"] = "Executives Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}


@section scripts{
    <script src="~/Scripts/Executives/ExecutivesIndex.js"></script>
}

    

<div class="box-content">

    <div class="box-heading">
        <div class="box-title">
            <h3 class="mb-35">Executives Panel</h3>
        </div>
        <div class="box-breadcrumb">
            <a class="btn btn-default" asp-controller="Executives" asp-action="CreateExecutive">Add Executives</a>
        </div>
    </div>

    <div class="row">

        <div class="col-xl-12 col-12">
            <div class="card-grid-2 hover-up">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="box-padding">
                            <div class="row display-list">
                                <div class="table-responsive">
                                    <table id="exicutivesList" class="stripe row-border">
                                        <thead align="center">
                                            <tr>
                                                <th>
                                                    Full Name
                                                </th>
                                                <th>
                                                    Designation
                                                </th>
                                                <th>
                                                    Primary Phone No.
                                                </th>
                                               
                                                <th>
                                                    Email
                                                </th>
                                               
                                                <th>
                                                    Password
                                                </th>
                                               
                                                <th>
                                                    Action
                                                </th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {

                                                <tr>
                                                   
                                                    <td>
                                                        <p class="color-text-paragraph font-sm" align="justify">@Html.DisplayFor(modelItem => item.ExFirstName + item.ExLastName)  </p>
                                                    </td>
                                                    <td>
                                                        <p class="color-text-paragraph font-sm" align="justify">  @Html.DisplayFor(modelItem => item.Designation)</p>
                                                    </td>
                                                    <td>
                                                        <p class="color-text-paragraph font-sm" align="justify"> @Html.DisplayFor(modelItem => item.Phone1)</p>
                                                    </td>
                                                    <td>
                                                        <p class="color-text-paragraph font-sm" align="justify"> @Html.DisplayFor(modelItem => item.Email)</p>

                                                    </td>
                                                    <td>
                                                        <p class="color-text-paragraph font-sm" align="justify"> @Html.DisplayFor(modelItem => item.Password)</p>

                                                    </td>@*
                                                    <td>
                                                        <p class="color-text-paragraph font-sm" align="justify"> <p>&nbsp;</p><img src="@item.Image" style="display: block;" /></p>

                                                    </td>*@
                                                    
                                                    <td>
                                                        <a asp-action="EditExecutive" class="" asp-route-id="@item.ExecutiveId"><i class='fas fa-edit' style='font-size:25px;color:black'></i></a> |
                                                        <a onclick="btnDelete(@item.ExecutiveId)"><i class='fas fa-trash-alt' style='font-size:25px;color:red'></i></a>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>